name: Build & Scan

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  GIT_USER: maxdoma
  IMAGE_NAME: ${{ github.repository }}
  VER: 1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        # (i think about not/existing repo, tag..)
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        # uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }} # ${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.VER }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      
      # Snan image
      # a. Compare the image built in the pull request with the one in production
      - name: Docker Scout
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: ${{ steps.meta.outputs.tags }} # ${{ env.USER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} 
          # to-env: production
          # ignore-unchanged: true
          # only-severities: critical,high
          github-token: ${{ secrets.GITHUB_TOKEN }}